### ISSUE TITLE
[Question] prefix-free requirement on labels

### ISSUE THREAD

**Issue by alxiong** [dalek-cryptography/merlin#62]
In the current [doc](https://merlin.cool/use/protocol.html?highlight=prefix#defining-a-transcript-protocol) on Transcript Protocol:
> "A sufficient condition for the transcript to be parseable is that the labels should be distinct and none should be a prefix of any other."

"parseable" is only relevant with debug feature on, right?

I don't quite follow why those labels needs to be prefix-free of each other.

Appreciate the clarification in advance!

**Comment by hdevalence** [comment]
Hey, thanks for asking about this!  This concern is independent of the debug feature, it's about having the transcript actually cryptographically bind the data it contains.

For instance, you could imagine some construction that tried to bind to byte strings `a` and `b` by hashing `a || b`, but because the lengths of `a` and `b` aren't included in the data that gets hashed, an attacker could cut up `a || b` differently as `a' || b'` and get the same hash value.

To prevent this, the encoding of the values that get fed into the hash should be structured so that it is in principle possible to parse it and recover the values.  Merlin uses a tag-length-value encoding to try to achieve this.  The tags are given by the label parameters, and they can be variable-length.  If the labels are prefix-free, then the transcript encoding is guaranteed to be parseable with no context: just read the tag, the length, and then that much data.  However, if one of the labels is a prefix of the other, then it might not be possible to distinguish them.  In practice, it's likely that for any specific protocol, the transcript would still be parseable for other reasons or with other context, but making the labels prefix-free gives a guarantee.

So roughly the requirement goes like this: prefix-free labels imply parseable transcript implies that the transcript binds to the data it includes.  But each implication is a sufficient condition, not a necessary one.

**Comment by alxiong** [comment]
Thanks @hdevalence for the explanation.

I can see the potential collision without prefix-free requirement, 2 more follow-up questions:

- I don't see why we need to "parse" it out. AFAIU, these messages (consists of label, len and values) are absorbed into the sponge and then later on used to produce challenges. I can't think of a case where these messages need to be extracted out from the sponge. (am I missing something?)

- Even if assuming we need to parse it, why not the following way:  I remember Boneh's textbook have a dedicated section on how to turn prefix-free PRF into fully secure PRF, the relevant one in our case is method 2, using prefix-free encoding since we want this to be deterministic and consistent for prover and verifier ([section 6.6.1](https://toc.cryptobook.us/book.pdf#subsection.6.6.1)). So, my question is, following the proposals in section 6.6.1, we could either 
  - prepend the length -- use len_tag-len_val-tag-value, instead of putting len in the middle which could be malleable as you hinted
  - or using stop bit -- which isn't quite necessary since we don't need this to be streaming

Thanks!

**Comment by hdevalence** [comment]
On your first question: it's not that we need to ever actually parse the transcript data in practice, but that *if it is possible* to parse the transcript data, then the data is encoded unambiguously. So one way to ensure that the data is encoded unambiguously is to convince ourselves that it's possible to write a parser for it.  However, this isn't the only way -- that's why being able to parse the transcript is a sufficient but not a necessary condition.

On the second question, the reason not to include the tag lengths is that it adds extra data (hashing overhead), and the labels are supposed to be fixed strings (that's why they're `&'static [u8]`, in order to push API users towards that usage).  In practice, even if there is a prefix, it is likely still the case that the transcript encodes data unambiguously, but it might take a little more thought to convince ourselves that that's the case.

**Comment by alxiong** [comment]
right, got it. Thanks!
